apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bedrock-dashboard
  name: bedrock-dashboard
  namespace: bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-dashboard
  template:
    metadata:
      labels:
        app: bedrock-dashboard
    spec:
      containers:
      - name: api
        image: 
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
      automountServiceAccountToken: false
